weLOVEholdings/intranet-mobile

App.js, package-lock.json, src/components/Header/Header.js, src/components/IconButtonWithText/IconButtonWithText.js, src/screens/Companies.js, src/screens/Home.js, src/screens/Intelligence.js, src/screens/Objectives.js, src/screens/Reports.js, src/screens/Sales.js, src/screens/Timeline.js
=> fix invariant violation error

App.js, src/components/IconButtonWithText/styles.js, src/screens/Home.js, src/screens/Timeline.js, src/styles/global.js, src/utils/storage.js
async storage item setter/getter
home page greeter
=> async storage item setter/getter

App.js, src/screens/Home.js, src/screens/Reports.js, src/screens/Timeline.js, src/utils/dateSetter.js
home and report page integration
=> home and report page integration

App.js, package-lock.json, src/components/Modals/Dayplan.js, src/screens/Login.js, src/screens/Reports.js, src/styles/global.js
=> reports modal form

src/components/Modals/Actions.js, src/components/Modals/Dayplan.js
=> reports fetch post action

android/app/build.gradle, android/app/src/main/java/com/sample/MainApplication.java, android/settings.gradle, ios/Podfile, package.json, src/components/Modals/Dayplan.js, yarn.lock
=> added style on dayplan

src/components/Modals/Actions.js, src/screens/Home.js, src/screens/Objectives.js, src/screens/Reports.js, src/screens/Timeline.js, src/utils/dateSetter.js
=> home page api integration

App.js, src/components/Header/styles.js, src/components/Modals/Actions.js, src/components/Modals/Dayplan.js, src/screens/Companies.js, src/screens/Home.js, src/screens/Intelligence.js, src/screens/Login.js, src/screens/Objectives.js, src/screens/Reports.js, src/screens/Sales.js, src/screens/Timeline.js, src/styles/global.js
report index views and api and some styling(ttimeline, reports, header, etc)
=> report index views and api

App.js, src/screens/Home.js, src/screens/Login.js
api call for weekly objectives
=> api call for weekly objectives

src/components/Modals/Actions.js, src/components/Modals/Eod.js, src/screens/Home.js, src/screens/Reports.js
create day plan and eod report
=> create day plan and eod report

src/components/Modals/Actions.js, src/components/Modals/Dayplan.js, src/components/Modals/Status.js, src/components/Modals/Weekly.js, src/components/Modals/styles.js, src/screens/Reports.js, src/styles/global.js
views and api integration for all reports
=> views and api integration for all reports

src/screens/Home.js
home collapsible display for reports
=> home collapsible display for reports

App.js, android/app/src/main/res/values/strings.xml, src/components/Header/styles.js, src/screens/Companies.js, src/screens/Home.js, src/screens/Intelligence.js, src/screens/Objectives.js, src/screens/Reports.js, src/screens/Sales.js, src/screens/Timeline.js, src/styles/global.js
- update styling of pages to match website
- fix bug in the timeline page
- fix display for objectives type of report in timeline
- add condition in navigation initialroutename to check if token is present
- fix display for homepage and report
=> update styling of pages to match website

src/components/Header/styles.js, src/components/IconButtonWithText/IconButtonWithText.js, src/screens/Home.js, src/styles/global.js
Create Branch for Home Page Style Fix
=> Home Page Style Fix

src/components/Header/styles.js, src/components/IconButtonWithText/styles.js, src/screens/Home.js
update some styling in the header and nav
=> update some styling in the header and nav

App.js, src/screens/Home.js, src/screens/Login.js, src/utils/storage.js
=> login homepage redirection

android/gradle.properties, src/components/IconButtonWithText/styles.js, src/screens/Home.js, src/screens/Login.js, src/screens/Timeline.js
1. home, timeline, reports these font need to be bold : check on web version
2. Objective boxes width should be all same : check web version
3. Weekly goals ,Day Plans, End of the day reports : NEED TO USE SMALL ARROW FOR THE COLLAPSABLE COMPONENT
4. Tag text of DAY PLAN , OBJECTIVE ( which has grey background ) that text Should be little small : check web version
5. Little less padding from top fir the first day plan to be started there is too much space
=> fix reviews from QA, 3-27

src/components/Header/Header.js, src/screens/Home.js, src/screens/Objectives.js, src/screens/Timeline.js
=> objecive page

src/screens/Objectives.js
integration of codes styling and api for objectives page
=> integration of codes styling and api for objectives page

src/screens/Companies.js, src/screens/Home.js, src/screens/Intelligence.js, src/screens/Objectives.js, src/screens/Reports.js, src/screens/Sales.js, src/screens/Timeline.js, src/styles/global.js
fix gray background and margin
=> fix gray background and margin

src/screens/Home.js, src/screens/Objectives.js, src/screens/Reports.js
fix for Objectives create and update progress
=> fix for Objectives create and update progress

package-lock.json, package.json, src/components/Modals/Dayplan.js, src/components/Modals/Eod.js, src/components/Modals/Status.js, src/components/Modals/Weekly.js, src/components/Modals/styles.js, src/screens/Reports.js
Fix for QA reviews
1. That should not be grey
2. All should be white background
3. There should NOT be cross button
4. Use back arrow at top left corner to navigate throughout the app
5. Every background should be white , neither grey nor blue
=> improvement for modals

src/components/Modals/Dayplan.js, yarn.lock
fix child scroll view inside Reports modal
=> fix child scroll view

src/components/Modals/Actions.js, src/components/Modals/Dayplan.js
=> fix for creating reports

src/components/Modals/Dayplan.js, src/components/Modals/Eod.js, src/components/Modals/Status.js, src/components/Modals/Weekly.js, src/components/Modals/styles.js
adjusted reports modal text editor height
=> adjusted reports modal text editor height

src/components/Modals/Dayplan.js, src/components/Modals/Eod.js, src/components/Modals/Status.js, src/components/Modals/Weekly.js, src/components/Modals/styles.js, src/screens/Timeline.js
fix for report modals
- text editor height and make it scrollable
timeline display for reports and status
=> fix for report modals

src/components/Modals/Actions.js, src/components/Modals/Dayplan.js, src/components/Modals/Eod.js, src/components/Modals/Status.js, src/components/Modals/Weekly.js, src/screens/Reports.js
fix issues and improvement for reports
=> fix issues and improvement for reports

src/screens/Objectives.js
=> fix objectives page

App.js, src/components/Modals/Dayplan.js, src/components/Modals/Eod.js, src/components/Modals/Status.js, src/components/Modals/Weekly.js, src/screens/Reports.js, src/screens/Timeline.js, src/screens/TimelineNew.js, src/styles/global.js
=> lazy loading in timeline
